# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Automation Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get Code
      uses: actions/checkout@v4.1.5
    
    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20
        
    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.11
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d tests/results tests/

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        # Token to access the API and report path
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: tests/results
    
    - name: Upload Report
      uses: actions/upload-artifact@v4.3.3
      if: always()
      with:
        name: Test E2E Report
        path: tests/results
